-- Task:  Use the COUNT function to count the number of movies for each IMDB rating. So, the query results should have a column of IMDB ratings and a "count" column. The IMDB rating column should list all the different IMDB ratings, for example, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, and so on, the corresponding count column cell should have the number of movies with that rating.
--       
--        Example
--        | imdb_rating | count |
--        | ----------- | ----- |
--        | 1           | 2     |
--        | 1.3         | 1     |
--        | 1.4         | 4     |
--        | 1.5         | 2     |
--        | 1.6         | 10    |
--        
-- Order the results by IMDB rating in ascending order, and only get the First 10 rows/results. --